name: Always Fail

on: [push, pull_request]

jobs:
  fail_job:
    runs-on: ubuntu-latest
    steps:
      - name: Intentional failure
        run: |
          echo "This test will always fail."
          exit 1
